<a href="https://colab.research.google.com/github/AnatoliyZhuk/Knowledge/blob/main/Introduction_to_Data_Science_Michigan_University_Coursera/Week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

+ Python - высокоуровневый язык программирования (оптимизирован для чтения людьми) <br/>
+ Python - интерпретируемый язык (нескомпилирован в машинный код, используется в интерактивном режиме - выполняется строка за строкой) <br/>
+ Python - динамически типизированный язык (при объявлении переменной, можно назначить ее целым числом, а на следующей строке назначить ее строкой)<br/>

<h1>Неделя №1<h1>



<h2>Python Functions<h2>

Здесь представлена самая обычная функция, которая позволяет сложить два числа.

In [1]:
def add_numbers(x, y):
  return x + y

add_numbers(1, 2)

3

Немного усложним функцию и передадим параметр $z$

In [2]:
def add_numbers(x, y, z):
  return x + y + z

add_numbers(1, 2, 3)

6

В данном примере $z$ необязательный параметр

In [4]:
def add_numbers(x, y, z = None):
  if z == None:
    return x + y
  if z != None:
    return x + y + z

add_numbers(3, 4, 2)  

9

В данной функции переменная **Flag** является ограничителем. Если **Flag** принимает значение **True**, то продолжаются дальнейшие действия, связанные с вычислением. Если **Flag** принимает значение **False**, то ничего не возвращается после использования функции.

In [5]:
def add_numbers(x, y, z = None, Flag = False):
  if Flag:
    print('Flag is True')
    if z == None:
      return x + y
    else:
      return x + y + z

print(add_numbers(1, 2, 3, Flag=True))
print(add_numbers(1, 2, Flag=False))

Flag is True
6
None


В этой функции в зависимости от ввода переменной **kind**, можно влиять на ход выполнения функции. 

In [ ]:
def do_math(a, b, kind=input()):
  if (kind=='add'):
    return a+b
  else:
    return a-b

print(do_math(1, 2))

nnn
-1


<h2>Python Types and Sequences<h2>

In [ ]:
print(type('This is a string'))
print(type(None))
print(type(1.0))
print(type(1))
print(type(sum_numbers))

<class 'str'>
<class 'NoneType'>
<class 'float'>
<class 'int'>
<class 'function'>


Типы последовательностей, о которых мы будем говорить: 
+ Tuples (кортежи)
+ Lists (списки)
+ Dictionaries (словари)

Кортеж - последовательность переменных, которая является неизменной, он не может быть изменен после создания. Записываются кортежи с помощью круглых скобок **( )**. Допускается смещивание типов данных внутри кортежа. <br/>
Списки - похожи на кортежи, однако являются изменяемыми. Вы можете изменить их длину и значения элементов. Списки объявляются с помощью квадратных скобок **[ ]**. Для изменения списка можно использовать функцию **.append()**
Списки и кортежи являются итерируемыми типами (для них можно писать циклы)

In [ ]:
z = (1, 'did', 4, 'done')
print(type(z))

w = [1, 'did', 4, 'done']
print(type(w))

x = [1, 'did', 4, 'done']
x.append(3.3)
print(x)

for item in z:
  print(item, end=' ')

<class 'tuple'>
<class 'list'>
[1, 'did', 4, 'done', 3.3]
1 did 4 done 

In [ ]:
i = 0 
while i != len(x):
  print(x[i], end=' ')
  i += 1

1 did 4 done 3.3 

Мы можем проводить операции со списками:

In [ ]:
print([1, 2] + [3, 4])
print([1, 2] * 3)
print(1 in [1, 2, 4])

[1, 2, 3, 4]
[1, 2, 1, 2, 1, 2]
True


In [19]:
x = 'This is a Spring'
print(x[0])
print(x[0:2])
print(x[-1])
print(x[0:-2])
print(x[:3])
print(x[3:])

T
Th
g
This is a Spri
Thi
s is a Spring


Базовые инструменты для текстового анализа <br/>

In [25]:
first_name = 'Cristopher'
last_name = 'Brooks'
print(first_name + ' ' + last_name)
print((first_name + ' ') * 3)

Cristopher Brooks
Cristopher Cristopher Cristopher 


In [30]:
first_name = 'Conor Cristopher Arthur Hansen'.split(' ')[0]
last_name = 'Brooks Zhuk McGregor Li'.split(' ')[-2]
print(first_name + ' ' + last_name)

Conor McGregor


Словарь - содержит набор элементов, его отличие в том, что элементы помечены лейблами, которые не имеют порядка (для каждого элемента есть ключ. Используются **{ }** для обозначения словаря <br/>

In [31]:
x = {'Conor McGregor' : 'ConorMc@mail.ru', 'Cristopher Brooks' : 'Cris95@mail.ru'}
x['Conor McGregor']

'ConorMc@mail.ru'

Например, мы можем связать e-mail адреса с именами людей:

<h2> Python More on Strings <h2>

In [32]:
print('Anatoliy' + str(95))

Anatoliy95


<h2>Python Dates and Times<h2>

Дата и время могут храниться разными способами.<br/>
Один из наиболее устаревших методов хранения даты и времени основан на смещении от эпохи (взятое за основу время 1 января 1970 года)<br/>
Нередко можно видеть системы хранящие дату транзакции в секундах или милисекундах с этой даты. Если вы видите большие значения там, где предполагается увидеть дату и время их нужно преобразовать.

In [ ]:
import datetime as dt
import time as tm

In [ ]:
# возвращает число секунд прошедших с начала эпохи (1 января 1970 года время: 00.00 Часовой пояс на 3 часа меньше, чем в МСК)
amount_sec = tm.time() 
amount_sec

1608229518.3645637

In [ ]:
# Возвращает дату, которая находится на расстоянии определенного количества секунд
# В скобках указано количество секунд, прошедшее с начала эпохи
data_future = dt.datetime.fromtimestamp(amount_sec)
print(data_future)
print(data_future.year, data_future.month, data_future.day, data_future.hour, data_future.minute, data_future.second, data_future.microsecond)

2020-12-17 17:44:24.177991
2020 12 17 17 44 24 177991


In [ ]:
# Аналог fromtimestamp
local_time = tm.ctime(11)
local_time

'Thu Jan  1 00:00:11 1970'

In [ ]:
# Возвращает дату настоящего момента
now = dt.datetime.now()
now

datetime.datetime(2020, 12, 17, 18, 25, 57, 42288)

In [ ]:
# Вычисляем число, которое было определенное количество дней назад
delta = dt.timedelta(days=100)
today = dt.date.today()
print(delta)
print(today)
print(today - delta)

100 days, 0:00:00
2020-12-17
2020-09-08


<h2>Advanced Python Objects, map()<h2>

Вы не объявляете переменные внутри объекта, вы просто начинаете их использовать.
Переменные класса могут быть объявлены. Это переменные которые совместно используются во всех экземплярах. Кокретно в этом примере мы подразумеваем, что все люди находятся в **School of Information**.

In [ ]:
class Person:
  department = 'School of information'

Функция **map()** является основой для функционального программирования в Python.<br/>
В функиональном программировании явно объявляются все параметры, которые могут измениться путем выполения данной функции

In [ ]:
do_one = [1, 2, 4, 6]
do_two = [3, 1, 5, 3]
chop = list(map(lambda x : x + 1, do_one))
print(chop)

[2, 3, 5, 7]


<h2> Manipulating Text with Regular Expression <h2>

In [5]:
import re

text = 'This is a good day'
if re.search('good', text):
  print('Wonderful')
else:
   print('Absence')

Wonderful


In [8]:
text = 'Amy works diligently. Amy gets good grades. Our student Amy is succesful.'
print(re.split('Amy', text))
print(re.findall('Amy', text))

['', ' works diligently. ', ' gets good grades. Our student ', ' is succesful.']
['Amy', 'Amy', 'Amy']


In [6]:
import requests
from bs4 import BeautifulStoneSoup as Soup


url = 'https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%BA%D0%B3%D1%80%D0%B5%D0%B3%D0%BE%D1%80,_%D0%9A%D0%BE%D0%BD%D0%BE%D1%80'


source = requests.get(url)
main_text = source.text
soup = Soup(main_text)

data = soup.find('div', {'class': 'mw-parser-output'})
print(data)

<div class="mw-parser-output"><div class="hatnote dabhide">В Википедии есть статьи о других людях с такой фамилией, см. <a class="mw-disambig" href="/wiki/%D0%9C%D0%B0%D0%BA%D0%B3%D1%80%D0%B5%D0%B3%D0%BE%D1%80" title="Макгрегор">Макгрегор</a>.</div>
<table class="infobox" data-name="Боец смешанного стиля" style=""><tbody><tr><th class="infobox-above" colspan="2" style="background:#eaecf0;"><style data-mw-deduplicate="TemplateStyles:r113288029">.mw-parser-output .ts_Спортсмен_имя{position:relative}.mw-parser-output .ts_Спортсмен_имя .icon{display:flex;align-items:center;position:absolute;top:0;bottom:0;left:0}.mw-parser-output .ts_Спортсмен_имя .icon img{display:block}.mw-parser-output .ts_Спортсмен_имя .label{margin:0 2em}@media(min-width:720px){.mw-parser-output .ts_Спортсмен_имя{margin:.15em}}body.skin-minerva .mw-parser-output .ts_Спортсмен_имя{margin:0}</style><div class="ts_Спортсмен_имя"><div class="icon" style=""><a class="image" href="/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:MMA_pictogra

/usr/local/lib/python3.7/dist-packages/bs4/__init__.py:568: UserWarning: The BeautifulStoneSoup class is deprecated. Instead of using it, pass features="xml" into the BeautifulSoup constructor.
  'The BeautifulStoneSoup class is deprecated. Instead of using '


In [3]:
with open('datasets/Макгрегор,_Конор.txt', 'r') as file:
  wiki = file.read()

FileNotFoundError: ignored

<h2> Quiz <h2>

**Задание №1**

In [ ]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


**Задание №2**

$L_2 = \sqrt{\sum_{i=1}^n (a_i - b_i)^2}$

Предположим, что $a$ и $b$ - два (20, 20) массивa numpy. Расстояние $L_2$ (определенное выше) между двумя массивами равных размеров может быть вычислено в Python следующим образом:

In [36]:
import numpy as np
a = np.array([[1, 3, 5], [2, 4, 6], [1, 3, 5]])
b = np.array([[7, 8, 3], [2, 5, 4], [2, 4, 6]])

def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result

Какое из следующих выражений, использующих эту функцию, приведет к ошибке?

+ l2_dist(a, b)
+ l2_dist(a.T, b.T)
+ l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20, 1)))
+ l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20)))

In [40]:
l2_dist(np.reshape(a, (3 * 3)), np.reshape(b, (3 * 3)))

8.54400374531753

In [ ]:
b1 = np.reshape(xix, (2, 6), order='A')
b1

array([[1, 3, 5, 2, 4, 6],
       [1, 3, 5, 1, 3, 5]])

In [ ]:
b1[0 : 2, 0 : 2]

array([[1, 3],
       [1, 3]])

**Задание №3**

In [62]:
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

In [67]:
a5.shape

(4,)

In [52]:
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a4.ndim)

[0.00826127 0.27490424 0.64725534 0.15982307]
[[0.43476554]
 [0.34251163]
 [0.8496797 ]
 [0.84784069]]
[[1 2 3 4]]
[1 2 3]
[1. 2. 3. 4.]
1


**Задание №4**

In [54]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


**Задание №5**

In [57]:
massiv = np.array([[0, 1, 2, 3, 4, 5],
          [6, 7, 8, 9, 10, 11],
          [12, 13, 14, 15, 16, 17],
          [18, 19, 20, 21, 22, 23],
          [24, 25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34, 35]])

massiv[2:4, 2:4]

array([[14, 15],
       [20, 21]])

**Задание №6**


In [58]:
import re
s = 'ACBCAC'

In [61]:
print(re.findall('^AC', s))
print(re.findall('AC', s))
print(re.findall('^[AC]', s))
print(re.findall('[^A]C', s))

['AC']
['AC', 'AC']
['A']
['BC']


**Задание №7**

In [ ]:
import re

s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)

L

5

**Задание №10**

In [75]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = '\(.\)' 
print(len(re.findall(pattern,text)))

4
